### ISSUE TITLE
Install via Homebrew cask?

### ISSUE THREAD

**Issue by jonathanlaniado** [FuzzyIdeas/MusicDecoy#1]
Would you be able to add the app to Homebrew?

**Comment by alin23** [comment]
Yes, I just published it, didn't have time for adding to brew. Will do it later.

**Comment by alin23** [comment]
Waiting for approval here: https://github.com/Homebrew/homebrew-cask/pull/159213

**Comment by alin23** [comment]
Done! `brew install music-decoy` should work now

**Comment by jonathanlaniado** [comment]
Wow, great job getting this done so quickly. Thank you, installed!
