### ISSUE TITLE
VLC crashes when this is open

### ISSUE THREAD

**Issue by Fizzadar** [FuzzyIdeas/MusicDecoy#3]
I've no idea why, but VLC crashes when trying to play any media while music decoy is running, very odd!

**Comment by alin23** [comment]
This is documented in the README 😊 https://github.com/FuzzyIdeas/MusicDecoy#vlc-crashes

**Comment by Fizzadar** [comment]
Oh how embarrassing! Sorry for the pointless issue!

**Comment by AllSystemsOnline** [comment]
Finding this two days ago could have saved me resetting my Mac and reinstalling all my applications from scratch.

*facepalm*
