### ISSUE TITLE
Is there a way to make open Spotify?

### ISSUE THREAD

**Issue by ebisbe** [FuzzyIdeas/MusicDecoy#4]
I never use and haven't used since 10+ years the music app but I can't remove it. This app works well to prevent opening it but if spotify is closed for any reason hitting the play button does nothing. Is there a way to chose a 'default' app to open? That would be really helpful

**Comment by alin23** [comment]
This app cannot do that because of how it works, but noTunes can do that: https://github.com/tombonez/noTunes
